FROM node:16-alpine3.14

WORKDIR /usr/src/app

COPY . .

RUN npm install

RUN npm run build

RUN npm run api-docs

# Get secret from git action
ARG PROD_DATABASE_URL
ARG PROD_DATABASE_USER
ARG PROD_DATABASE_PASSWORD
ARG PROD_DATABASE_NAME
ARG LOG_PATH

# Copy secret to ENV
ENV NODE_ENV=production \
 PROD_DATABASE_URL=$PROD_DATABASE_URL \
 PROD_DATABASE_USER=$PROD_DATABASE_USER \
 PROD_DATABASE_PASSWORD=$PROD_DATABASE_PASSWORD \
 PROD_DATABASE_NAME=$PROD_DATABASE_NAME \
 LOG_PATH=$LOG_PATH

EXPOSE 8000

CMD ["node", "dist/src/server.js"]
