openapi: 3.1.0
info:
  version: 1.0.0
  title: 무인도 API DOCS
  description: 무인도 backend api 문서
  contact:
    email: gkqkehs0321@gmail.com
tags:
  - name: AuthController
    description: 인증 관련 api
  - name: UserController
    description: 유저 관련 api
  - name: LetterController
    description: 편지 관련 api
paths:
  /v1/auth/sign-in:
    post:
      tags:
        - AuthController
      summary: 회원가입 및 로그인
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - deviceId
              properties:
                deviceId:
                  type: string
                  description: 기기 고유 Id
                  example: aweofiawe-23
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        description: accessToken
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVVVJRCI6Ijc0M2Y0ZjJhLTA2NmMtNGE1ZS1hMGI2LWUyZjBjMzIxNDEyNSIsImlhdCI6MTY5NTI2NTk0MX0.aEHb1pbcn6_V-j5Wg0X62ZjlvqWQXP5ThvcYxAxnTRo
                      nickname:
                        type: string
                        description: 유저 닉네임
                        example: tom
                      point:
                        type: number
                        description: 읽을 수 있는 개수
                        example: 0
                      send:
                        type: number
                        description: 이제 까지 보낸 개수
                        example: 0
                      receive:
                        type: number
                        description: 이제 까지 읽은 개수
                        example: 0
                      sound:
                        type: boolean
                        description: 배경화면 설정 여부
                        example: true
                      alarm:
                        type: boolean
                        description: 알람 수락 여부
                        example: true
  /v1/users/me:
    patch:
      tags:
        - UserController
      summary: 유저 정보 수정
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - nickname
                - sound
                - alarm
              properties:
                nickname:
                  type: string
                  description: 바꾸려는 닉네임
                  example: changeNickname
                sound:
                  type: boolean
                  description: 사운드 설정 여부
                  example: true
                alarm:
                  type: boolean
                  description: 알람 설정 여부
                  example: true
      responses:
        '200':
          description: 유저 정보 수정 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      nickname:
                        type: string
                        description: 유저 닉네임
                        example: tom
                      point:
                        type: number
                        description: 읽을 수 있는 개수
                        example: 0
                      send:
                        type: number
                        description: 이제 까지 보낸 개수
                        example: 0
                      receive:
                        type: number
                        description: 이제 까지 읽은 개수
                        example: 0
                      sound:
                        type: boolean
                        description: 배경화면 설정 여부
                        example: true
                      alarm:
                        type: boolean
                        description: 알람 수락 여부
                        example: true
  /v1/letters:
    post:
      tags:
        - LetterController
      summary: 편지 작성 하기
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: 편지 내용 (최소 10글자 최대 200글자)
                  example: 오늘 하루도 힘내세요!!
      responses:
        '200':
          description: 편지 작성 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    description: 편지 작성 성공
                    example: true
        '400':
          description: 비속어 포함
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: BAD_REQUEST
                  code:
                    type: number
                    example: 1201
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Slang word includes in letter
        '401':
          description: 메세지 길이 너무 짧음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: BAD_REQUEST
                  code:
                    type: number
                    example: 1203
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example:
                          message too short!
        '402':
          description: 메세지 길이 너무 김
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: BAD_REQUEST
                  code:
                    type: number
                    example: 1204
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: message too long!
  /v1/letters/random:
    get:
      tags:
        - LetterController
      summary: 랜덤 편지 읽기
      parameters:
        - in: header
          name: Authorization
          description: accessToken
          required: true
      responses:
        '200':
          description: 편지 읽기 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user:
                        type: string
                        example: 착한사람
                        description: 작성 유저
                      content:
                        type: string
                        example: 오늘 행복한 하루 되세요~
                        description: 편지 내용
                      like:
                        type: number
                        example: 0
                        description: 공감 개수
        '400':
          description: 포인트가 없어서 읽기 불가
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: BAD_REQUEST
                  code:
                    type: number
                    example: 1202
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Point not enough
        '401':
          description: 읽을 수 있는 편지가 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: INTERNAL_SERVER_ERROR
                  code:
                    type: number
                    example: 1205
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Letter not left, you read all letter
  /v1/letters/{letterUUID}:
    get:
      tags:
        - LetterController
      summary: 특정 편지 읽기
      parameters:
        - in: header
          name: Authorization
          description: accessToken
          required: true
        - name: letterUUID
          in: path
          description: 편지 UUID
          required: true
      responses:
        '200':
          description: 편지 읽기 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user:
                        type: string
                        example: 착한사람
                        description: 작성 유저
                      content:
                        type: string
                        example: 오늘 행복한 하루 되세요~
                        description: 편지 내용
                      like:
                        type: number
                        example: 0
                        description: 공감 개수
        '400':
          description: 존재하지 않는 편지
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: INTERNAL_SERVER_ERROR
                  code:
                    type: number
                    example: 1200
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Letter not found
        '401':
          description: 포인트가 없어서 읽기 불가
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: BAD_REQUEST
                  code:
                    type: number
                    example: 1202
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Point not enough
  /v1/letters/{letterUUID}/like:
    post:
      tags:
        - LetterController
      summary: 특정 편지 공감하기
      parameters:
        - name: Authorization
          in: header
          description: accessToken
          required: true
        - name: letterUUID
          in: path
          description: 편지 UUID
          required: true
      responses:
        '200':
          description: 특정 편지 공감 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: boolean
                    example: true
        '400':
          description: 존재하지 않는 편지
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: INTERNAL_SERVER_ERROR
                  code:
                    type: number
                    example: 1200
                  errors:
                    type: object
                    properties:
                      message:
                        type: string
                        example: Letter not found
