name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  build-and-push-image-to-dockerHub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/commit:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}       
            LOG_PATH=${{ secrets.LOG_PATH }}

  code-deploy:
    needs: build-and-push-image-to-dockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Access to server and Run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd commit
            docker-compose down
            docker-compose rm
            docker rmi ${{ secrets.IMAGE_NANE }} 
            docker pull ${{ secrets.IMAGE_NANE }} 
            docker-compose up -d
